# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-27 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0002_game_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(null=True, upload_to='image_uploads'),
        ),
    ]
