# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-11 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0008_remove_payments_paid_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='games',
            field=models.ManyToManyField(null=True, to='storefront.Game'),
        ),
    ]
