# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-11 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0009_auto_20170211_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='games',
            field=models.ManyToManyField(to='storefront.Game'),
        ),
    ]
