# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-13 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0012_gamerating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamerating',
            name='rating',
            field=models.IntegerField(default=1),
        ),
    ]
