# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-23 05:10
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0013_auto_20170212_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='payments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='game',
            name='price',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
