# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-23 05:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0014_auto_20170222_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='publication_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='payments',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
