# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-25 06:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0016_api_auth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='api_auth',
            name='id',
        ),
        migrations.AlterField(
            model_name='api_auth',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
