# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-26 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0017_auto_20170224_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_vaidated',
            field=models.BooleanField(default=False),
        ),
    ]
